#Source files
SRCS	=	./ft_isalpha.c
			./ft_isdigit.c
			./ft_isalnum.c
			./ft_isascii.c
			./ft_isprint.c
			./ft_strlen.c
			./ft_memset.c
			./ft_bzero.c
			./ft_memcpy.c
			./ft_memmove.c
			./ft_strlcpy.c
			./ft_strlcat.c
			./ft_toupper.c
			./ft_tolower.c
			./ft_strchr.c
			./ft_strrchr.c
			./ft_strncmp.c
			./ft_memchr.c
			./ft_memcmp.c
			./ft_strnstr.c
			./ft_atoi.c
			./ft_calloc.c
			./ft_strdup.c
	
			./ft_ft_substr.c
			./ft_ft_strjoin.c
			./ft_ft_strtrim.c
			./ft_ft_split.c
			./ft_ft_itoa.c
			./ft_ft_strmapi.c
			./ft_ft_striteri.c
			./ft_ft_putchar_fd.c
			./ft_ft_putstr_fd.c
			./ft_ft_putstr_fd.c
			./ft_ft_putendl_fd.c
			./ft_ft_putnbr_fd.c
			./ft_.c
			./ft_.c


CC = gcc
CFLAGS = -Wall -Wextra -Werror

$(CC) $(CFLAGS) -c file.c

%.o = %.c
	$(CC) -c $< -o